Output "/Users/kaypark/workspace/colorscheme/lazygit-nepes/docs/dark.gif"
Set Width 1280
Set Height 720
Set FontSize 14

Hide
Type "cd ~/workspace/colorscheme/nepes-palette"
Enter
Sleep 0.5s
Type "LG_CONFIG_FILE=~/workspace/colorscheme/lazygit-nepes/nepes-dark.yml lazygit"
Enter
Sleep 2s
Show
Screenshot "/Users/kaypark/workspace/colorscheme/lazygit-nepes/docs/dark.png"
Sleep 1s
Type "2"
Sleep 1s
Type "q"
